// Generated by gencpp from file cctv_layer_ros/Coordinate.msg
// DO NOT EDIT!


#ifndef CCTV_LAYER_ROS_MESSAGE_COORDINATE_H
#define CCTV_LAYER_ROS_MESSAGE_COORDINATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cctv_layer_ros
{
template <class ContainerAllocator>
struct Coordinate_
{
  typedef Coordinate_<ContainerAllocator> Type;

  Coordinate_()
    : x(0)
    , y(0)  {
    }
  Coordinate_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;

   typedef int16_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::cctv_layer_ros::Coordinate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cctv_layer_ros::Coordinate_<ContainerAllocator> const> ConstPtr;

}; // struct Coordinate_

typedef ::cctv_layer_ros::Coordinate_<std::allocator<void> > Coordinate;

typedef boost::shared_ptr< ::cctv_layer_ros::Coordinate > CoordinatePtr;
typedef boost::shared_ptr< ::cctv_layer_ros::Coordinate const> CoordinateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cctv_layer_ros::Coordinate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cctv_layer_ros::Coordinate_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cctv_layer_ros::Coordinate_<ContainerAllocator1> & lhs, const ::cctv_layer_ros::Coordinate_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cctv_layer_ros::Coordinate_<ContainerAllocator1> & lhs, const ::cctv_layer_ros::Coordinate_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cctv_layer_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cctv_layer_ros::Coordinate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cctv_layer_ros::Coordinate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cctv_layer_ros::Coordinate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cctv_layer_ros::Coordinate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cctv_layer_ros::Coordinate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cctv_layer_ros::Coordinate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cctv_layer_ros::Coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d78a6b8c9650c754bf0432d3d1707c3";
  }

  static const char* value(const ::cctv_layer_ros::Coordinate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d78a6b8c9650c75ULL;
  static const uint64_t static_value2 = 0x4bf0432d3d1707c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::cctv_layer_ros::Coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cctv_layer_ros/Coordinate";
  }

  static const char* value(const ::cctv_layer_ros::Coordinate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cctv_layer_ros::Coordinate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n"
"int16 y\n"
;
  }

  static const char* value(const ::cctv_layer_ros::Coordinate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cctv_layer_ros::Coordinate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Coordinate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cctv_layer_ros::Coordinate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cctv_layer_ros::Coordinate_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int16_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CCTV_LAYER_ROS_MESSAGE_COORDINATE_H
